# Gains for the Internal Velocity Joint Controller
# P and D gains for each axis.
pid_int: 
 #proportional 
 gains_p: [3, 3, 3, 3, 3, 3]
 
 #derivative 
 gains_d: [0.75, 1.45, 1.45, 0.65, 0.65, 0.65]

 #integral 
 gains_i: [1.0, 2.25, 2.25, 1, 1, 1]

