# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
sosm_opctrl: 
 #proportional [130.0, 320.0, 300.0, 155.0, 75.0, 100.0]
 gains_p: [672, 672, 672, 672, 140, 132]
 
 #derivative [80.0, 40.0, 40.0, 45.0, 40.0, 40.0][3.0, 3.0, 3.0, 3.0, 3.0, 3.0]
 gains_d: [79, 79, 72, 64, 11, 50]

 #integral [70.10, 150.10, 150.10, 100.10, 70.10, 80.10]
 gains_i: [1.0, 2.25, 2.25, 1, 1, 1]

 #damping stop 
 gains_d_stop: [10, 10, 10, 10, 10, 10]

 #External torque activation threshold (for the norm(tau))
 ext_ntau_thresh: 0.5

 #Threshold for the determinant
 min_detJ: 0.01

 #min q3 to avoid singularitites
 q3_limit: 10.0

 #Bias
 lambda: 10.0
 kappa: 10.0
