# Gains for the Impedance Cartesian (Position) Space Controller
# P and D gains for each axis.
x_imp_ctrl: 
 #proportional 
 gains_p: [15, 15, 15]
 
 #derivative 
 gains_d: [1, 1, 1]

 #interaction gain (per joint) 
 gains_int: [1, 1, 1, 1, 1, 1]

 # Desired position in deg
 goal: [0.5, -0.5, 0.5]
